### ISSUE TITLE
`readImageAuto` is much slower than `readImage`

### ISSUE THREAD

**Issue by ksqsf** [lehins/massiv-io#3]
A minimal benchmark program:

```haskell
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE ViewPatterns #-}
module Main where

import Data.Massiv.Array as Array
import Data.Massiv.Array.IO
import System.Environment
import Criterion.Measurement

printTime :: String -> Double -> IO Double
printTime nm ts = do
  t <- getTime
  putStrLn $ nm <> ": " <> show (t - ts)
  pure t

main :: IO ()
main = do
  initializeTime
  args <- getArgs
  let path = args !! 0
  putStrLn ("open file: " ++ path)
  t0 <- getTime
  -- !image <- readImage path :: IO (Image S (Alpha (SRGB 'NonLinear)) Word8)
  !image <- readImageAuto path :: IO (Image S (Alpha (SRGB 'NonLinear)) Word8)
  t1 <- printTime "Read" t0
  !image' <-
    computeIO $ Array.map greenify $ image :: IO (Image S (Alpha (SRGB 'NonLinear)) Word8)
  t2 <- printTime "Greenify" t1
  !_ <- writeImage "/tmp/output.png" image'
  _ <- printTime "Write" t2
  pure ()
  where
    greenify pix@(toPixelD -> PixelRGBA r g b a) =
      let r' = r ** 1.5
          g' = g ** 0.8
          b' = b ** 1.5
      in toPixel8 (PixelRGBA r' g' b' a)
```

[A sample image file (~8MB)](https://user-images.githubusercontent.com/23358293/138227354-824abcd4-8715-45ca-8ee1-54a7e4a8f23e.png)

`readImage`:

```
Read: 0.3348495239915792
Greenify: 1.1122988749993965
Write: 1.3883658600097988
```

`readImageAuto` (`-O2`, `+RTS -N1`)

```
Read: 19.073593208988314
Greenify: 1.113029093001387
Write: 1.4160580450115958
```

`readImageAuto` (`-O2`, `+RTS -N6`)

```
Read: 4.292046625996591
Greenify: 0.2290665229957085
Write: 1.41482026099402
```

Both are still slower than an equivalent Rust program (using the `image` crate): which can complete the task in ~1second using a single core (`cargo run --release ~/Desktop/image.png  0.94s user 0.04s system 99% cpu 0.989 total`).

```rust
use image::io::Reader as ImageReader;
use image::Rgba;
use std::env;
use std::io::Result;

fn main() {
    let args = env::args().collect::<Vec<_>>();
    let path = &args[1];
    println!("open file: {}", path);
    let mut img = ImageReader::open(path).unwrap().decode().unwrap();
    let mut buf = img.as_mut_rgba8().unwrap();
    let pixels = buf.pixels_mut();
    for Rgba([r, g, b, a]) in pixels {
        *r = ((*r as f64 / 256.0).powf(1.5) * 256.0) as u8;
        *g = ((*g as f64 / 256.0).powf(0.8) * 256.0) as u8;
        *b = ((*b as f64 / 256.0).powf(1.5) * 256.0) as u8;
    }
    img.save("/tmp/rust.png").unwrap();
}
```

**Comment by lehins** [comment]
As I suspected, problem was with ghc needing some inline pragmas. It is now a bit unfortunate that we need to worry about it, but one way or another the fixed is on master with runtimes:

With regard to Rust, it looks like at least for me Rust is still at least 2 times faster:
```
$ time cargo run --release /tmp/repro.png 
real	0m1.332s
user	0m1.246s
sys	0m0.057s
```
vs Haskell
```
$ git checkout debug-auto-read
$ stack build && time stack exec -- auto-read /tmp/repro.png
Read: 0.3288113449816592
Greenify: 1.3393165160086937
Write: 1.3171642170054838

real	0m3.326s
user	0m3.169s
sys	0m0.116s
```

We could of course cheat a bit. In Rust we get safe inplace mutation, while in Haskell+massiv we get free parallelization, so we can speed up a bit more with a flag:

````
$ stack build && time stack exec -- auto-read /home/lehins/tmp/repro.png +RTS -N7
open file: /home/lehins/tmp/repro.png
Read: 0.3495126560155768
Greenify: 0.3119399959978182
Write: 1.321218606986804

real	0m2.330s
user	0m4.038s
sys	0m0.081s
````

That being said, for this particular case there are few things at play that could be improved, which aren't as easy as adding an `INLINE` pragma or supplying a flag. Unfortunately, I don't have an easy fix for those issues, although I do have some long term plans for some of them. To name a few:

* in the Rust case greenifyng happens in place using mutable array. In some distant future we'll hopefully have support for linear types in massiv, which would allow us do the exact same thing
* current Color library isn't as efficient as it could be with Alpha channels and Pixels in general, due to Haskell's limitation of inability to unpack polymorphic types. Very hard thing to figure out, so hopefully one day... Not a low hanging fruit.
* conversion of images (encode/decode) is out of my hands and out of my domain expertise too. It looks like 50% of runtime comes from JuicyPixels encoding the file. It would be nice if someone could dedicate some effort into optimizing that.

@ksqsf Please, try out a fix on master and let me know how it goes. As soon as I hear from you I'll make a release on hackage. These are some worthwhile performance fixes that I'd be happy to release ASAP. And thank you for making this bug report!

**Comment by ksqsf** [comment]
Yes, the latest commit seems to fix this problem! The GHC optimizer is like dark magic to me... And thanks for your investigation!

```
Read: 0.3766352749953512
Greenify: 1.1712964680045843
Write: 1.5020932389888912
```

I myself am not an expert in image processing either so I cannot say anything valuable here, but I really look forward to safe in-place mutability. :)

**Comment by lehins** [comment]
@ksqsf Thanks for this report. Released a new minor version with these performance improvements: [`massiv-io-1.0.0.1`](https://hackage.haskell.org/package/massiv-io-1.0.0.1)
